image_base: /home/jon/railCal8D_data/
images:
 - my_camera_000_000.jpg
 - my_camera_000_001.jpg
 - my_camera_000_002.jpg
 - my_camera_000_003.jpg
 - my_camera_000_004.jpg
 - my_camera_000_005.jpg
 - my_camera_000_006.jpg
 - my_camera_000_007.jpg
 - my_camera_000_008.jpg
 - my_camera_000_009.jpg
 - my_camera_000_010.jpg
 - my_camera_000_011.jpg
 - my_camera_000_012.jpg
 - my_camera_000_013.jpg
 - my_camera_000_014.jpg
 - my_camera_000_015.jpg
 - my_camera_001_000.jpg
 - my_camera_001_001.jpg
 - my_camera_001_002.jpg
 - my_camera_001_003.jpg
 - my_camera_001_004.jpg
 - my_camera_001_005.jpg
 - my_camera_001_006.jpg
 # - my_camera_001_007.jpg
 # - my_camera_001_008.jpg
 - my_camera_001_009.jpg
 - my_camera_001_010.jpg
 # - my_camera_001_011.jpg
 # - my_camera_001_012.jpg
 # - my_camera_001_013.jpg
 - my_camera_002_000.jpg
 - my_camera_002_001.jpg
 - my_camera_002_002.jpg
 - my_camera_002_003.jpg
 - my_camera_002_004.jpg
 - my_camera_002_005.jpg
 - my_camera_002_006.jpg
 - my_camera_002_007.jpg
 - my_camera_002_008.jpg
 - my_camera_002_009.jpg
 - my_camera_002_010.jpg
 - my_camera_002_011.jpg
 - my_camera_002_012.jpg
 - my_camera_002_013.jpg
 - my_camera_002_014.jpg
 - my_camera_002_015.jpg
 - my_camera_003_000.jpg
 - my_camera_003_001.jpg
 - my_camera_003_002.jpg
 - my_camera_003_003.jpg
 - my_camera_003_004.jpg
 - my_camera_003_005.jpg
 - my_camera_003_006.jpg
 - my_camera_003_008.jpg
 - my_camera_003_009.jpg
 - my_camera_003_010.jpg
 - my_camera_003_011.jpg
 - my_camera_003_012.jpg
 - my_camera_003_013.jpg
 - my_camera_003_014.jpg
 - my_camera_003_015.jpg
 - my_camera_004_000.jpg
 - my_camera_004_004.jpg
 - my_camera_004_010.jpg
 - my_camera_004_011.jpg
 - my_camera_004_012.jpg
 - my_camera_004_013.jpg
 - my_camera_004_014.jpg
 - my_camera_004_015.jpg
 - my_camera_005_001.jpg
 - my_camera_005_003.jpg
 - my_camera_005_004.jpg
 - my_camera_005_008.jpg
 - my_camera_005_010.jpg
 # - my_camera_005_011.jpg
 - my_camera_005_012.jpg
 - my_camera_005_013.jpg
 - my_camera_005_014.jpg
 - my_camera_006_000.jpg
 - my_camera_006_004.jpg
 - my_camera_006_008.jpg
 - my_camera_006_009.jpg
 - my_camera_006_010.jpg
 - my_camera_006_011.jpg
 - my_camera_006_012.jpg
 - my_camera_006_013.jpg
 # - my_camera_006_014.jpg
 - my_camera_007_001.jpg
 - my_camera_007_002.jpg
 - my_camera_007_003.jpg
 - my_camera_007_004.jpg
 - my_camera_007_005.jpg
 - my_camera_007_006.jpg
 - my_camera_007_007.jpg
 - my_camera_007_008.jpg
 - my_camera_007_009.jpg
 - my_camera_007_010.jpg
 - my_camera_007_011.jpg
 - my_camera_007_012.jpg
 - my_camera_007_013.jpg
 - my_camera_007_014.jpg
 - my_camera_007_015.jpg
 - my_camera_008_000.jpg
 - my_camera_008_002.jpg
 - my_camera_008_007.jpg
 - my_camera_008_008.jpg
 - my_camera_008_009.jpg
 - my_camera_008_010.jpg
 - my_camera_008_011.jpg
 - my_camera_008_012.jpg
 - my_camera_008_013.jpg
 - my_camera_008_014.jpg
 - my_camera_008_015.jpg
 - my_camera_009_000.jpg
 - my_camera_009_001.jpg
 - my_camera_009_002.jpg
 - my_camera_009_003.jpg
 - my_camera_009_004.jpg
 - my_camera_009_005.jpg
 - my_camera_009_006.jpg
 - my_camera_009_007.jpg
 - my_camera_009_008.jpg
 - my_camera_009_009.jpg
 - my_camera_009_010.jpg
 - my_camera_009_011.jpg
 - my_camera_009_012.jpg
 - my_camera_009_013.jpg
 - my_camera_009_014.jpg
 - my_camera_009_015.jpg
 - my_camera_010_000.jpg
 - my_camera_010_001.jpg
 - my_camera_010_002.jpg
 - my_camera_010_003.jpg
 - my_camera_010_004.jpg
 - my_camera_010_005.jpg
 - my_camera_010_006.jpg
 - my_camera_010_007.jpg
 - my_camera_010_008.jpg
 - my_camera_010_009.jpg
 - my_camera_010_010.jpg
 - my_camera_010_011.jpg
 - my_camera_010_012.jpg
 - my_camera_010_013.jpg
 - my_camera_010_014.jpg
 - my_camera_010_015.jpg
 - my_camera_011_000.jpg
 - my_camera_011_001.jpg
 - my_camera_011_002.jpg
 - my_camera_011_003.jpg
 - my_camera_011_004.jpg
 - my_camera_011_005.jpg
 - my_camera_011_006.jpg
 - my_camera_011_007.jpg
 - my_camera_011_008.jpg
 - my_camera_011_009.jpg
 - my_camera_011_010.jpg
 - my_camera_011_011.jpg
 - my_camera_011_012.jpg
 - my_camera_011_013.jpg
 - my_camera_011_014.jpg
 - my_camera_011_015.jpg
 - my_camera_012_000.jpg
 - my_camera_012_001.jpg
 - my_camera_012_002.jpg
 - my_camera_012_003.jpg
 - my_camera_012_004.jpg
 - my_camera_012_005.jpg
 - my_camera_012_006.jpg
 - my_camera_012_007.jpg
 - my_camera_012_008.jpg
 - my_camera_012_009.jpg
 - my_camera_012_010.jpg
 - my_camera_012_011.jpg
 - my_camera_012_012.jpg
 - my_camera_012_013.jpg
 - my_camera_012_014.jpg
 - my_camera_012_015.jpg
 - my_camera_013_000.jpg
 - my_camera_013_001.jpg
 - my_camera_013_002.jpg
 - my_camera_013_003.jpg
 - my_camera_013_004.jpg
 - my_camera_013_005.jpg
 - my_camera_013_006.jpg
 - my_camera_013_007.jpg
 - my_camera_013_008.jpg
 - my_camera_013_009.jpg
 - my_camera_013_010.jpg
 - my_camera_013_011.jpg
 - my_camera_013_012.jpg
 - my_camera_013_013.jpg
 - my_camera_013_014.jpg
 - my_camera_013_015.jpg
 - my_camera_014_000.jpg
 - my_camera_014_001.jpg
 - my_camera_014_002.jpg
 - my_camera_014_003.jpg
 - my_camera_014_004.jpg
 - my_camera_014_005.jpg
 - my_camera_014_006.jpg
 - my_camera_014_007.jpg
 - my_camera_014_008.jpg
 - my_camera_014_009.jpg
 - my_camera_014_010.jpg
 - my_camera_014_011.jpg
 - my_camera_014_012.jpg
 - my_camera_014_013.jpg
 - my_camera_014_014.jpg
 - my_camera_014_015.jpg
 - my_camera_015_000.jpg
 - my_camera_015_001.jpg
 - my_camera_015_002.jpg
 - my_camera_015_003.jpg
 - my_camera_015_004.jpg
 - my_camera_015_005.jpg
 - my_camera_015_006.jpg
 - my_camera_015_007.jpg
 - my_camera_015_008.jpg
 - my_camera_015_009.jpg
 - my_camera_015_010.jpg
 - my_camera_015_011.jpg
 - my_camera_015_012.jpg
 - my_camera_015_013.jpg
 - my_camera_015_014.jpg
 - my_camera_015_015.jpg
